pulls:
# Enable for pull requests
  perform: true
      Thanks for pulling the code!
# Customize a comment to post on a pull request. Comment out to use the default
#  comment:

issues:
# enable for issues
  perform: true
# issues with these labels will be considered. Set to `[]` to disable for issues
  labels:
    - help wanted
    - good first issue
      Thanks for raising a issue! we will look into it
# Customize a comment to post on an issue. Comment out to use the default
#  comment:
